// Auto-generated by scripts/generate-tcg-art.js — illustrator-style art for
// Trainer/Stadium cards, hosted on Supabase. Do not edit by hand.
export default {
  "trainer-potion": "https://bphnyyiwwcetryafgjof.supabase.co/storage/v1/object/public/tcg-art/trainer-potion.png",
  "trainer-super-potion": "https://bphnyyiwwcetryafgjof.supabase.co/storage/v1/object/public/tcg-art/trainer-super-potion.png",
  "trainer-poke-ball": "https://bphnyyiwwcetryafgjof.supabase.co/storage/v1/object/public/tcg-art/trainer-poke-ball.png",
  "trainer-great-ball": "https://bphnyyiwwcetryafgjof.supabase.co/storage/v1/object/public/tcg-art/trainer-great-ball.png",
  "trainer-energy-search": "https://bphnyyiwwcetryafgjof.supabase.co/storage/v1/object/public/tcg-art/trainer-energy-search.png",
  "trainer-switch": "https://bphnyyiwwcetryafgjof.supabase.co/storage/v1/object/public/tcg-art/trainer-switch.png",
  "trainer-research": "https://bphnyyiwwcetryafgjof.supabase.co/storage/v1/object/public/tcg-art/trainer-research.png",
  "trainer-hop": "https://bphnyyiwwcetryafgjof.supabase.co/storage/v1/object/public/tcg-art/trainer-hop.png",
  "trainer-stadium-spa": "https://bphnyyiwwcetryafgjof.supabase.co/storage/v1/object/public/tcg-art/trainer-stadium-spa.png",
  "trainer-stadium-arena": "https://bphnyyiwwcetryafgjof.supabase.co/storage/v1/object/public/tcg-art/trainer-stadium-arena.png"
};
