// HTTP routes for the read-along Reading Mode. Distinct from the
// battle-based Story Mode (server-modules/story.js) — this is just
// content delivery: a list endpoint + a story-by-id endpoint. No
// auth required; the content is for kids and contains no PII.
//
//   GET /api/reading/stories        — list summaries (no section text)
//   GET /api/reading/stories/:id    — full story including section text + audio URLs
//
// Audio: section.audioUrl is filled in at request time from a manifest
// at shared/reading-stories-manifest.json (generated by
// scripts/generate-tts.js). The story content itself stays canonical;
// the manifest is the volatile bit that updates each time TTS runs.

const fs = require("node:fs");
const path = require("node:path");
const { listStories, getStory } = require("../shared/reading-stories");

const MANIFEST_PATH = path.join(__dirname, "..", "shared", "reading-stories-manifest.json");

let _manifest = null;
let _manifestMtime = 0;

function loadManifest() {
  // Re-read if the file's mtime changed (catches a fresh deploy that
  // shipped a new manifest without rolling the lambda).
  try {
    const stat = fs.statSync(MANIFEST_PATH);
    if (_manifest && stat.mtimeMs === _manifestMtime) return _manifest;
    _manifest = JSON.parse(fs.readFileSync(MANIFEST_PATH, "utf8"));
    _manifestMtime = stat.mtimeMs;
    return _manifest;
  } catch (err) {
    // Manifest missing = no audio yet; return empty object so the UI
    // gracefully shows "Audio coming soon" buttons.
    _manifest = {};
    _manifestMtime = 0;
    return _manifest;
  }
}

function hydrateAudio(story) {
  if (!story) return story;
  const manifest = loadManifest();
  const sections = story.sections.map((sec) => {
    const key = `${story.id}/${sec.id}`;
    const entry = manifest[key];
    return entry ? { ...sec, audioUrl: entry.audioUrl } : sec;
  });
  return { ...story, sections };
}

function mount(app) {
  app.get("/api/reading/stories", (_req, res) => {
    res.json({ stories: listStories() });
  });

  app.get("/api/reading/stories/:id", (req, res) => {
    const story = getStory(req.params.id);
    if (!story) return res.status(404).json({ error: "Story not found." });
    res.json({ story: hydrateAudio(story) });
  });
}

module.exports = { mount, hydrateAudio, loadManifest };
